// Run before deploying the homepage after changing the separate game repo.
const fs = require('node:fs');
const path = require('node:path');
const { createHash } = require('node:crypto');

const source = path.resolve(process.argv[2] || path.join(__dirname, '..', 'square-game'), 'public');
const destination = path.join(__dirname, 'public');
const assets = ['app.js', 'styles.css'].map(name => ({ name, content: fs.readFileSync(path.join(source, name)) }));
let html = fs.readFileSync(path.join(source, 'index.html'), 'utf8');
for (const { name, content } of assets) {
  const version = createHash('sha256').update(content).digest('hex').slice(0, 12);
  html = html.replace(`/square-game/${name}`, `/square-game-assets/${name}?v=${version}`);
}
html = html.replace('/square-game/config.js', '/square-game-assets/config.js');
fs.mkdirSync(path.join(destination, 'square-game-assets'), { recursive: true });
for (const { name, content } of assets) fs.writeFileSync(path.join(destination, 'square-game-assets', name), content);
fs.writeFileSync(path.join(destination, 'square-game.html'), html);
// config.js belongs to the homepage deployment and is generated by build.js.
console.log(`Square Game browser files synchronized from ${source}`);
